<a href="https://colab.research.google.com/github/AkshayaReddy2006/23CSBTB27-28/blob/main/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
array=np.array([2,5,3,7,3])
print(array)
print(type(array))

[2 5 3 7 3]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
arry=np.array([[2,5],[4,2]])
arry1=np.array([[2,5,4,2],[4,2,1,0]])
arry2=np.array([[2,5,4],[4,2,5],[6,7,8]])
print(arry)
print(arry1)
print(arry2)

[[2 5]
 [4 2]]
[[2 5 4 2]
 [4 2 1 0]]
[[2 5 4]
 [4 2 5]
 [6 7 8]]


In [3]:
import numpy as np
array1=np.array([1,3,4,5,6])
array2=np.array([2,6,3,4,8])
print(array1)
print(np.add(array1,array2))
print(np.multiply(array1,array2))
print(np.subtract(array2,array1))
print(np.divide(array2,array1))
print(type(array1))

[1 3 4 5 6]
[ 3  9  7  9 14]
[ 2 18 12 20 48]
[ 1  3 -1 -1  2]
[2.         2.         0.75       0.8        1.33333333]
<class 'numpy.ndarray'>
